### ISSUE TITLE
I found this ERROR CLASS WITH \APP\CRUD\USERCOMPONENT NAMESPACE DOESN'T EXIST

### ISSUE THREAD

**Issue by syofyanzuhad** [rezaamini-ir/laravel-easypanel#34] opened 2021-11-12 09:36 UTC
I want to make a CRUD for the User model, but it return this error
![Screenshot from 2021-11-12 16-35-25](https://user-images.githubusercontent.com/52684582/141445073-a2202d1e-3267-4445-862c-febaa1c97750.png)

![Screenshot from 2021-11-12 16-35-42](https://user-images.githubusercontent.com/52684582/141445002-e53c5a09-b262-4043-a6ea-549946d6f372.png)

CLASS WITH \APP\CRUD\USERCOMPONENT NAMESPACE DOESN'T EXIST
![Screenshot from 2021-11-12 16-33-12](https://user-images.githubusercontent.com/52684582/141444810-171fb274-473d-463a-9f06-d284bcb6953c.png)

**Comment by rezaamini-ir** [comment] 2021-11-28 15:55
This problem has been fixed in 1.8.0 version.

**Closed by rezaamini-ir** 2021-11-28 15:55 UTC

**Comment by rezaamini-ir** [comment] 2022-05-03 08:35
https://github.com/rezaamini-ir/laravel-easypanel/issues/52#issuecomment-1115849649

**Comment by johnsenga** [comment] 2022-08-15 10:35
I had the same problem. I noticed the problem is occurring in line 18 of helpers.php. The offending line is this
`        if (!file_exists(app_path("/CRUD/{$name}Component.php")) or !class_exists($namespace)){`
The $name parameter is passed in lowercase and therefore file_exists() for the path of the component will fail in Linux where cases are strict.
I added a line before the above line and the error went away. This is only a temp solution and a better fix is needed.
`$name=ucwords($name);`

**Comment by erdum** [comment] 2023-02-14 16:05
I encountered the same problem due to case sensitivity on line number 18 and 34.
I just put this line before lines 18 and 34 as suggested by @johnsenga in [Comment #34](https://github.com/rezaamini-ir/laravel-easypanel/issues/34#issuecomment-1214870607)
`$name = ucwords($name)`

I am using PHP 8.1 on Ubuntu 22 LTS

**Comment by ea57-ua** [comment] 2023-10-30 15:43
I've the same problem working on Ubuntu 22.04 LTS using php 8.1 and composer 2.2.4.
Thank you @johnsenga for the solution!
